import Head from 'next/head';
import Contact from './components/Contact/Contacts';
import Footer from './components/Footer/Footer';
import Navigation from './components/Navigation/Navigation';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ scrollBehavior: 'smooth' }}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Paytone+One&family=Poppins:wght@300;400;500&display=swap"
          rel="stylesheet"
        />
      </head>

      <body>
        <Navigation />
        {children}
        <Contact />
        <Footer />
      </body>
    </html>
  );
}
